const sampleUsers = [
  {
    name: 'Sarah Jenkins',
    email: 'sarah.instructor@eduvibe.com',
    password: 'password123',
    role: 'instructor',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&auto=format&fit=crop&q=80',
    headline: 'Senior Full Stack Engineer & Google Developer Expert',
    bio: '12+ years of industry experience architecting scalable distributed systems and training 100,000+ engineers globally in modern React, Node, and Cloud technologies.',
    website: 'https://sarahjenkins.dev',
    github: 'https://github.com/sarahjenkins',
    linkedin: 'https://linkedin.com/in/sarahjenkins',
  },
  {
    name: 'Michael Chen',
    email: 'michael.instructor@eduvibe.com',
    password: 'password123',
    role: 'instructor',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    headline: 'Principal AI Researcher & Python Specialist',
    bio: 'Former ML Engineer at OpenAI and Stanford guest lecturer. Dedicated to making Deep Learning and Generative AI accessible to everyone.',
    website: 'https://chen-ai.io',
    github: 'https://github.com/michaelchen-ai',
    linkedin: 'https://linkedin.com/in/michaelchen-ai',
  },
  {
    name: 'David Miller',
    email: 'david.instructor@eduvibe.com',
    password: 'password123',
    role: 'instructor',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    headline: 'Lead Product Designer & UX Strategist',
    bio: 'Designed award-winning applications at top tech firms. Specializing in Figma systems, UI micro-interactions, and conversion-centered UX design.',
    website: 'https://davidmiller.design',
    github: 'https://github.com/davidmiller-ux',
    linkedin: 'https://linkedin.com/in/davidmiller-ux',
  },
  {
    name: 'Alex Johnson',
    email: 'student@eduvibe.com',
    password: 'password123',
    role: 'student',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=300&auto=format&fit=crop&q=80',
    headline: 'Aspiring Full-Stack Software Developer',
    bio: 'Building real-world web and mobile applications with modern stacks.',
  },
  {
    name: 'Emily Davis',
    email: 'emily@eduvibe.com',
    password: 'password123',
    role: 'student',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&auto=format&fit=crop&q=80',
    headline: 'Data Enthusiast & Python Learner',
  },
  {
    name: 'EduVibe Admin',
    email: 'admin@eduvibe.com',
    password: 'password123',
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1628157582853-a796fa650a6a?w=300&auto=format&fit=crop&q=80',
    headline: 'Platform Master Administrator',
    bio: 'Overseeing course quality assurance and platform operations.',
  },
];

const sampleCourses = [
  {
    title: 'Complete 2026 MERN Stack Developer Masterclass',
    subtitle: 'Master React 19, Node.js, Express, MongoDB, Socket.io, Redux Toolkit, and Stripe by building 4 production apps.',
    description: `Welcome to the most complete, modern, and up-to-date **MERN Stack Masterclass** on the web! In this comprehensive course, you will learn how to build enterprise-grade, lightning-fast full-stack web applications from scratch.

### What you will achieve:
- Architect scalable backend REST & Real-time APIs with **Node.js, Express, MongoDB, and Socket.io**
- Build pixel-perfect, responsive, and accessible client user interfaces with **React, Tailwind CSS, and Vite**
- Implement industry-standard **JWT authentication**, secure password hashing, and role-based permissions
- Integrate **Stripe Payment Gateway** for seamless subscription and one-time checkout flows
- Deploy production applications to cloud platforms with CI/CD workflows.`,
    category: 'Web Development',
    level: 'All Levels',
    language: 'English',
    price: 89.99,
    discountPrice: 19.99,
    thumbnail: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&auto=format&fit=crop&q=80',
    trailerUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    rating: 4.9,
    numReviews: 482,
    studentsEnrolled: 3420,
    tags: ['React', 'Node.js', 'MongoDB', 'Express', 'Tailwind CSS', 'MERN'],
    learningObjectives: [
      'Build 4 full-stack real-world MERN web applications from scratch',
      'Master advanced React hooks, custom hooks, and state management',
      'Design high-performance MongoDB schemas with indexes and aggregation pipelines',
      'Integrate Stripe Checkout and Webhooks securely',
      'Implement real-time bidirectional messaging with Socket.io',
      'Deploy full-stack apps to Vercel and Render with SSL',
    ],
    requirements: [
      'Basic knowledge of HTML, CSS, and modern JavaScript (ES6+)',
      'A computer running Windows, macOS, or Linux with internet access',
      'No prior React or Node.js backend experience is required',
    ],
    targetAudience: [
      'Beginner to Intermediate developers looking to become job-ready Full-Stack Engineers',
      'Frontend developers wanting to master Node.js backend development',
      'Students looking to build rich portfolio projects that impress recruiters',
    ],
    sections: [
      {
        title: 'Section 1: Course Overview & Development Environment Setup',
        order: 1,
        lessons: [
          {
            title: 'Welcome & How to Get the Most from this Course',
            description: 'Introduction to course curriculum, Discord community, and GitHub repositories.',
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
            duration: 8,
            isPreview: true,
            resources: [
              { title: 'Full Course Cheatsheet PDF', url: 'https://example.com/cheatsheet.pdf', fileType: 'pdf' },
            ],
            order: 1,
          },
          {
            title: 'Modern Tooling Setup: Node, Vite, Tailwind, VS Code',
            description: 'Configuring our workspace with optimal extensions and formatting rules.',
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
            duration: 14,
            isPreview: true,
            resources: [],
            order: 2,
          },
        ],
      },
      {
        title: 'Section 2: Node.js & Express.js Deep Dive',
        order: 2,
        lessons: [
          {
            title: 'Event Loop, Streams, and Modular Architecture',
            description: 'Understanding asynchronous I/O and architectural patterns in Node.js.',
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
            duration: 22,
            isPreview: false,
            resources: [],
            order: 1,
          },
          {
            title: 'Building RESTful APIs with Express Routing and Middleware',
            description: 'Creating maintainable router structures and custom error handling.',
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
            duration: 28,
            isPreview: false,
            resources: [],
            order: 2,
          },
        ],
      },
      {
        title: 'Section 3: MongoDB & Advanced Mongoose Modeling',
        order: 3,
        lessons: [
          {
            title: 'Schema Design, Relations, Indexes, and Virtuals',
            description: 'Designing high throughput NoSQL schemas and compound indexes.',
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
            duration: 25,
            isPreview: false,
            resources: [],
            order: 1,
          },
          {
            title: 'Aggregation Pipelines & Complex Search Queries',
            description: 'Using $match, $lookup, $group, and $facet for performant reporting.',
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
            duration: 30,
            isPreview: false,
            resources: [],
            order: 2,
          },
        ],
      },
      {
        title: 'Section 4: React 19 Frontend Engineering',
        order: 4,
        lessons: [
          {
            title: 'Component Architecture & Custom Hooks',
            description: 'Creating clean reusable components and custom hooks for data fetching.',
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackSeeTheWorld.mp4',
            duration: 35,
            isPreview: false,
            resources: [],
            order: 1,
          },
          {
            title: 'State Management and React Router v6 Data Loaders',
            description: 'Mastering modern declarative routing and responsive layouts.',
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
            duration: 29,
            isPreview: false,
            resources: [],
            order: 2,
          },
        ],
      },
      {
        title: 'Section 5: Payments, Socket.io, and Production Deployment',
        order: 5,
        lessons: [
          {
            title: 'Integrating Stripe Checkout & Handling Webhook Signatures',
            description: 'Building secure end-to-end payment processing with idempotency.',
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
            duration: 32,
            isPreview: false,
            resources: [],
            order: 1,
          },
          {
            title: 'Real-Time Bi-Directional Features with Socket.io',
            description: 'Live notifications, room broadcasting, and instant Q&A threads.',
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4',
            duration: 26,
            isPreview: false,
            resources: [],
            order: 2,
          },
        ],
      },
    ],
  },
  {
    title: 'Generative AI & LLM Applications with Python & LangChain',
    subtitle: 'Build autonomous AI Agents, RAG pipelines, Vector Search with Pinecone, and Full-Stack AI Saas Apps.',
    description: `Dive into the cutting-edge world of **Generative AI, Large Language Models (LLMs), and Autonomous Multi-Agent Systems**.

This course guides you step-by-step through developing real-world AI applications powered by **OpenAI, Anthropic, LangChain, LlamaIndex, and Vector Databases**.`,
    category: 'Data Science & AI',
    level: 'Intermediate',
    language: 'English',
    price: 94.99,
    discountPrice: 24.99,
    thumbnail: 'https://images.unsplash.com/photo-1677442136019-21780efad99a?w=800&auto=format&fit=crop&q=80',
    trailerUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    rating: 4.95,
    numReviews: 290,
    studentsEnrolled: 2150,
    tags: ['AI', 'Python', 'LangChain', 'OpenAI', 'RAG', 'Machine Learning'],
    learningObjectives: [
      'Build Production-grade Retrieval-Augmented Generation (RAG) systems',
      'Create multi-agent autonomous workflows using LangGraph and AutoGen',
      'Embed documents and query Vector Databases like Chroma and Pinecone',
      'Fine-tune open-weight models using LoRA / QLoRA',
      'Deploy AI Microservices with FastAPI and Docker',
    ],
    requirements: [
      'Fundamental Python programming experience',
      'Basic understanding of API concepts and JSON',
    ],
    targetAudience: [
      'Software engineers transitioning into Applied AI & ML Engineering',
      'Data scientists seeking to build production software applications around LLMs',
    ],
    sections: [
      {
        title: 'Section 1: Foundations of Large Language Models & Prompt Engineering',
        order: 1,
        lessons: [
          {
            title: 'Transformer Architecture & Attention Mechanisms Explained',
            description: 'Visual intuition of how tokens, embeddings, and attention weights operate.',
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
            duration: 18,
            isPreview: true,
            resources: [],
            order: 1,
          },
          {
            title: 'Structured Outputs, Function Calling, and JSON Schema Enforcement',
            description: 'Reliable extraction of typed data using modern function calling APIs.',
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
            duration: 24,
            isPreview: false,
            resources: [],
            order: 2,
          },
        ],
      },
      {
        title: 'Section 2: Building Enterprise RAG Systems',
        order: 2,
        lessons: [
          {
            title: 'Chunking Strategies, Embeddings, and Hybrid Search',
            description: 'Semantic vector search combined with keyword BM25 filtering.',
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
            duration: 31,
            isPreview: false,
            resources: [],
            order: 1,
          },
        ],
      },
    ],
  },
  {
    title: 'UI/UX Design Masterclass: Figma to High-Converting Web Products',
    subtitle: 'Learn design systems, wireframing, interactive prototyping, micro-animations, and UX research methodologies.',
    description: `Master the art and science of **User Experience (UX) and User Interface (UI) Design**. Learn how top product designers at Apple, Airbnb, and Stripe turn complex business requirements into elegant, high-converting digital experiences.`,
    category: 'Design & UI/UX',
    level: 'Beginner',
    language: 'English',
    price: 69.99,
    discountPrice: 14.99,
    thumbnail: 'https://images.unsplash.com/photo-1581291518655-9523c932ded0?w=800&auto=format&fit=crop&q=80',
    trailerUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
    rating: 4.88,
    numReviews: 185,
    studentsEnrolled: 1840,
    tags: ['Figma', 'UI Design', 'UX Research', 'Design Systems', 'Product Design'],
    learningObjectives: [
      'Master Figma from scratch including Auto Layout, Variables, and Component Variants',
      'Create scalable design tokens and design systems used by Fortune 500 teams',
      'Conduct user interviews, usability testing, and wireframe user journeys',
      'Design interactive mobile app and desktop web prototypes with smart animations',
    ],
    requirements: [
      'No previous design or drawing skills needed',
      'Free Figma account',
    ],
    targetAudience: [
      'Aspiring UI/UX and Product Designers',
      'Frontend developers wishing to sharpen their aesthetic eye and UX skills',
    ],
    sections: [
      {
        title: 'Section 1: Design Fundamentals & Figma Mastery',
        order: 1,
        lessons: [
          {
            title: 'Visual Hierarchy, Typography Scales, and Color Psychology',
            description: 'Core principles of modern digital interface aesthetics.',
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
            duration: 20,
            isPreview: true,
            resources: [],
            order: 1,
          },
          {
            title: 'Mastering Auto Layout v5 & Responsive Constraints',
            description: 'Designing cards and navigations that adapt across any screen resolution.',
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
            duration: 25,
            isPreview: false,
            resources: [],
            order: 2,
          },
        ],
      },
    ],
  },
  {
    title: 'Modern Cloud & DevOps: Docker, Kubernetes & AWS CI/CD',
    subtitle: 'Containerize microservices, deploy to AWS ECS/EKS, configure Terraform IaC, and build GitHub Actions pipelines.',
    description: `Automate everything from development to production! This DevOps masterclass gives you real, hands-on experience deploying scalable cloud architectures on **Amazon Web Services (AWS)** using **Docker, Kubernetes, Terraform, and GitHub Actions**.`,
    category: 'Cloud & DevOps',
    level: 'Intermediate',
    language: 'English',
    price: 99.99,
    discountPrice: 29.99,
    thumbnail: 'https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=800&auto=format&fit=crop&q=80',
    trailerUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    rating: 4.92,
    numReviews: 210,
    studentsEnrolled: 1530,
    tags: ['Docker', 'Kubernetes', 'AWS', 'DevOps', 'CI/CD', 'Terraform'],
    learningObjectives: [
      'Containerize full-stack applications with multi-stage Dockerfiles',
      'Orchestrate clusters using Kubernetes Pods, Deployments, and Ingress controllers',
      'Automate cloud infrastructure provisioning using Terraform IaC',
      'Set up enterprise GitHub Actions CI/CD pipelines with zero-downtime deployment',
    ],
    requirements: [
      'Basic command-line (Linux/Bash) familiarity',
      'Basic knowledge of web server concepts',
    ],
    targetAudience: [
      'Software engineers wanting to gain DevOps & Cloud mastery',
      'System administrators transitioning to Cloud/DevOps Engineering',
    ],
    sections: [
      {
        title: 'Section 1: Docker Containers in Practice',
        order: 1,
        lessons: [
          {
            title: 'Container Architecture & Optimization Techniques',
            description: 'Building tiny, secure Alpine-based containers with multi-stage builds.',
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
            duration: 22,
            isPreview: true,
            resources: [],
            order: 1,
          },
        ],
      },
    ],
  },
  {
    title: 'Practical Ethical Hacking & Cybersecurity Fundamentals',
    subtitle: 'Learn network security, penetration testing, Web App Security (OWASP Top 10), and Kali Linux tools.',
    description: `Protect systems from modern cyber threats! Learn hands-on penetration testing and ethical hacking techniques in safe, controlled virtual lab environments.`,
    category: 'Cybersecurity',
    level: 'Beginner',
    language: 'English',
    price: 0,
    discountPrice: 0,
    thumbnail: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&auto=format&fit=crop&q=80',
    trailerUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackSeeTheWorld.mp4',
    rating: 4.87,
    numReviews: 340,
    studentsEnrolled: 4200,
    tags: ['Cybersecurity', 'Ethical Hacking', 'OWASP', 'Linux', 'Network Security'],
    learningObjectives: [
      'Understand how network protocols (TCP/IP, DNS, HTTPS) work and how they are intercepted',
      'Detect and remediate OWASP Top 10 vulnerabilities (SQLi, XSS, CSRF, IDOR)',
      'Perform vulnerability assessments using Nmap, Wireshark, and Burp Suite',
    ],
    requirements: [
      'Basic understanding of how the internet works',
    ],
    targetAudience: [
      'Anyone curious about ethical hacking and cybersecurity careers',
      'Web developers seeking to write secure code and prevent data breaches',
    ],
    sections: [
      {
        title: 'Section 1: Security Mindset & Lab Setup',
        order: 1,
        lessons: [
          {
            title: 'Setting up Kali Linux and Vulnerable Web Lab',
            description: 'Configuring VirtualBox or WSL for safe security experiments.',
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
            duration: 19,
            isPreview: true,
            resources: [],
            order: 1,
          },
        ],
      },
    ],
  },
  {
    title: 'React Native & Expo: Build iOS & Android Mobile Apps',
    subtitle: 'Cross-platform mobile development with React Native, Expo Router, Redux Toolkit, Push Notifications, and SQLite.',
    description: `Create production-ready native mobile applications for iOS and Android with a single JavaScript/TypeScript codebase!`,
    category: 'Mobile Development',
    level: 'Intermediate',
    language: 'English',
    price: 79.99,
    discountPrice: 16.99,
    thumbnail: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&auto=format&fit=crop&q=80',
    trailerUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4',
    rating: 4.91,
    numReviews: 162,
    studentsEnrolled: 1280,
    tags: ['React Native', 'Expo', 'Mobile', 'iOS', 'Android', 'JavaScript'],
    learningObjectives: [
      'Build native iOS and Android apps using React Native and Expo',
      'Handle gesture animations with Reanimated 3',
      'Integrate device sensors, camera, geolocation, and push notifications',
      'Publish applications to Apple App Store and Google Play Store',
    ],
    requirements: [
      'Comfortable with basic React principles (Components, State, Props)',
    ],
    targetAudience: [
      'Web developers wanting to expand into mobile app development',
    ],
    sections: [
      {
        title: 'Section 1: React Native Core & Expo Setup',
        order: 1,
        lessons: [
          {
            title: 'Expo Workflow & First Native Component',
            description: 'Understanding View, Text, StyleSheet, and Fast Refresh on real devices.',
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
            duration: 15,
            isPreview: true,
            resources: [],
            order: 1,
          },
        ],
      },
    ],
  },
];

module.exports = { sampleUsers, sampleCourses };
